import { IItem, OGlobalKey } from '../../types';

export const creaturesLoot: IItem[] = [
  {
    prefab: 'CelestialFeather',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 2,
      time: 60,
      availability: 3.5,
      complexity: 3,
      amountToSell: 1,
    },
  },
  {
    prefab: 'TrophyFallenValkyrie',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 4,
      time: 300,
      availability: 3.5,
      complexity: 3,
      amountToSell: 1,
    },
  },
  {
    prefab: 'CharredBone',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 1,
      time: 60,
      availability: 3.5,
      complexity: 2,
      amountToSell: 10,
    },
  },
  {
    prefab: 'TrophyCharredMelee',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 4,
      time: 180,
      availability: 3.5,
      complexity: 2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'TrophyCharredArcher',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 4,
      time: 180,
      availability: 3.5,
      complexity: 2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'TrophyCharredMage',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 5,
      time: 400,
      availability: 3.5,
      complexity: 3,
      amountToSell: 1,
    },
  },
  {
    prefab: 'MorgenSinew',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 3,
      time: 120,
      availability: 3.5,
      complexity: 3,
      amountToSell: 5,
    },
  },
  {
    prefab: 'MorgenHeart',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 3,
      time: 160,
      availability: 3.5,
      complexity: 3,
      amountToSell: 2,
    },
  },
  {
    prefab: 'TrophyMorgen',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 5,
      time: 360,
      availability: 3.5,
      complexity: 3,
      amountToSell: 1,
    },
  },
  {
    prefab: 'TrophyBonemawSerpent',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 5,
      time: 240,
      availability: 3.5,
      complexity: 2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'BoneMawSerpentMeat',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 3,
      time: 60,
      availability: 3.5,
      complexity: 2,
      amountToSell: 5,
    },
  },
  {
    prefab: 'BonemawSerpentTooth',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 3,
      time: 45,
      availability: 3.5,
      complexity: 2,
      amountToSell: 5,
    },
  },
  {
    prefab: 'TrophyAsksvin',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 4,
      time: 180,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 1,
    },
  },
  {
    prefab: 'AskBladder',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 2,
      time: 80,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 5,
    },
  },
  {
    prefab: 'AskHide',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 2,
      time: 60,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 5,
    },
  },
  {
    prefab: 'AsksvinMeat',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 2,
      time: 30,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 5,
      balanceCoefficient: 0.8,
    },
  },
  {
    prefab: 'VoltureMeat',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 1,
      time: 30,
      availability: 3.5,
      complexity: 1.5,
      amountToSell: 5,
    },
  },
  {
    prefab: 'VoltureEgg',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 1.5,
      time: 45,
      availability: 3.5,
      complexity: 1,
      amountToSell: 5,
    },
  },
  {
    prefab: 'TrophyVolture',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    sellable: true,
    pricing: {
      rarity: 3.5,
      time: 120,
      availability: 3.5,
      complexity: 1.5,
      amountToSell: 1,
    },
  },
  {
    prefab: 'CharredCogwheel',
    stack: 10,
    globalKeyToBuy: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 4,
      time: 120,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 1,
    },
  },
];
