import { BOSS_PRICE_BALANCE_MULTIPLIER } from '../../const';
import { IItem, OGlobalKey } from '../../types';

export const creaturesLoot: IItem[] = [
  {
    prefab: 'HareMeat',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 1,
      time: 30,
      availability: 3.5,
      complexity: 2,
      amountToSell: 5,
    },
  },
  {
    prefab: 'ScaleHide',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 1,
      time: 30,
      availability: 3.5,
      complexity: 2,
      amountToSell: 25,
    },
  },
  {
    prefab: 'TrophyHare',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    globalKeyToSell: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 3,
      time: 400,
      availability: 3.5,
      complexity: 2,
      amountToSell: 1,
      balanceCoefficient: 0.7,
    },
  },
  {
    prefab: 'GiantBloodSack',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 1,
      time: 30,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 25,
    },
  },
  {
    prefab: 'TrophyTick',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    globalKeyToSell: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 3,
      time: 200,
      availability: 3.5,
      complexity: 2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'BugMeat',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 1,
      time: 15,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 5,
    },
  },
  {
    prefab: 'Carapace',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 1,
      time: 40,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 10,
    },
  },
  {
    prefab: 'TrophySeeker',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    globalKeyToSell: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 3,
      time: 200,
      availability: 3.5,
      complexity: 2.5,
      amountToSell: 1,
    },
  },
  {
    prefab: 'Mandible',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 3,
      time: 120,
      availability: 3.5,
      complexity: 3,
      amountToSell: 5,
    },
  },
  {
    prefab: 'TrophySeekerBrute',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedYagluth,
    globalKeyToSell: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 3.5,
      time: 400,
      availability: 3.5,
      complexity: 3,
      amountToSell: 1,
      balanceCoefficient: 0.6,
    },
  },
  {
    prefab: 'TrophySeekerQueen',
    stack: 20,
    sellable: true,
    buyable: false,
    globalKeyToSell: OGlobalKey.defeatedQueen,
    pricing: {
      rarity: 1,
      time: 150,
      availability: 3.5,
      complexity: 3,
      amountToSell: 1,
      balanceCoefficient: BOSS_PRICE_BALANCE_MULTIPLIER,
    },
  },
];
