import { IItem, OGlobalKey } from '../../types';

export const creaturesLoot: IItem[] = [
  {
    prefab: 'WolfMeat',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 1,
      time: 20,
      availability: 2.5,
      complexity: 2,
      amountToSell: 10,
    },
  },
  {
    prefab: 'WolfFang',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 1.5,
      time: 40,
      availability: 2.5,
      complexity: 2,
      amountToSell: 10,
    },
  },
  {
    prefab: 'WolfPelt',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 1,
      time: 30,
      availability: 2.5,
      complexity: 2,
      amountToSell: 10,
    },
  },
  {
    prefab: 'TrophyWolf',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3,
      time: 200,
      availability: 2.5,
      complexity: 2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'FreezeGland',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 2,
      time: 50,
      availability: 2.5,
      complexity: 2.2,
      amountToSell: 10,
    },
  },
  {
    prefab: 'TrophyHatchling',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3,
      time: 200,
      availability: 2.5,
      complexity: 2.2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'TrophySGolem',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    globalKeyToSell: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3,
      time: 400,
      availability: 2.5,
      complexity: 3,
      amountToSell: 1,
      balanceCoefficient: 0.7,
    },
  },
  {
    prefab: 'TrophyFenring',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    globalKeyToSell: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3.5,
      time: 400,
      availability: 2.5,
      complexity: 2,
      amountToSell: 1,
      balanceCoefficient: 0.7,
    },
  },
  {
    prefab: 'TrophyUlv',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    globalKeyToSell: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3,
      time: 200,
      availability: 2.5,
      complexity: 2,
      amountToSell: 1,
    },
  },
  {
    prefab: 'JuteRed',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3,
      time: 120,
      availability: 2.5,
      complexity: 2.5,
      amountToSell: 5,
    },
  },
  {
    prefab: 'TrophyCultist',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    globalKeyToSell: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 4,
      time: 400,
      availability: 2.5,
      complexity: 2.5,
      amountToSell: 1,
      balanceCoefficient: 0.8,
    },
  },
  {
    prefab: 'WolfHairBundle',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedBonemass,
    pricing: {
      rarity: 3,
      time: 100,
      availability: 2.5,
      complexity: 2.5,
      amountToSell: 5,
    },
  },
  {
    prefab: 'WolfClaw',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3.2,
      time: 40,
      availability: 2.5,
      complexity: 2.5,
      amountToSell: 5,
    },
  },
];
