import { BOSS_PRICE_BALANCE_MULTIPLIER } from '../../const';
import { IItem, OGlobalKey } from '../../types';

export const creaturesLoot: IItem[] = [
  {
    prefab: 'TrophyGreydwarf',
    stack: 20,
    sellable: true,
    buyable: false,
    globalKeyToSell: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 3,
      time: 120,
      amountToSell: 1,
      availability: 1.5,
      complexity: 1,
    },
  },
  {
    prefab: 'TrophyGreydwarfBrute',
    stack: 20,
    sellable: true,
    buyable: false,
    globalKeyToSell: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 4,
      time: 120,
      amountToSell: 1,
      availability: 1.5,
      complexity: 1.5,
    },
  },
  {
    prefab: 'TrophyGreydwarfShaman',
    stack: 20,
    sellable: true,
    buyable: false,
    globalKeyToSell: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 3,
      time: 120,
      amountToSell: 1,
      availability: 1.5,
      complexity: 1.5,
    },
  },
  {
    prefab: 'TrophyFrostTroll',
    stack: 20,
    sellable: true,
    globalKeyToSell: OGlobalKey.defeatedEikthyr,
    globalKeyToBuy: OGlobalKey.defeatedTheElder,
    pricing: {
      rarity: 3,
      time: 120,
      amountToSell: 1,
      availability: 1.5,
      complexity: 2.5,
    },
  },
  {
    prefab: 'TrollHide',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 2,
      time: 40,
      amountToSell: 5,
      availability: 1.5,
      complexity: 2.5,
    },
  },
  {
    prefab: 'BoneFragments',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 1.5,
      time: 30,
      amountToSell: 25,
      availability: 1,
      complexity: 1.5,
    },
  },
  {
    prefab: 'TrophySkeleton',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedEikthyr,
    globalKeyToSell: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 3,
      time: 100,
      amountToSell: 1,
      availability: 1,
      complexity: 1.5,
    },
  },
  {
    prefab: 'TrophySkeletonPoison',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedEikthyr,
    globalKeyToSell: OGlobalKey.defeatedEikthyr,
    pricing: {
      rarity: 4,
      time: 300,
      amountToSell: 1,
      availability: 1,
      complexity: 1.5,
    },
  },
  {
    prefab: 'TrophyTheElder',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedTheElder,
    sellable: true,
    buyable: false,
    pricing: {
      rarity: 1,
      time: 60,
      amountToSell: 1,
      availability: 1.5,
      complexity: 2.5,
      balanceCoefficient: BOSS_PRICE_BALANCE_MULTIPLIER,
    },
  },
];
