import { BOSS_PRICE_BALANCE_MULTIPLIER } from '../../const';
import { IItem, OGlobalKey } from '../../types';

export const creaturesLoot: IItem[] = [
  {
    prefab: 'TrophyGoblin',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3,
      time: 200,
      availability: 3,
      complexity: 2.5,
      amountToSell: 1,
    },
  },
  {
    prefab: 'TrophyGoblinBrute',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3.5,
      time: 400,
      availability: 3,
      complexity: 3,
      amountToSell: 1,
      balanceCoefficient: 0.6,
    },
  },
  {
    prefab: 'TrophyGoblinShaman',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3.5,
      time: 400,
      availability: 3,
      complexity: 2.8,
      amountToSell: 1,
      balanceCoefficient: 0.6,
    },
  },
  {
    prefab: 'LoxMeat',
    stack: 20,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 1,
      time: 20,
      availability: 3,
      complexity: 3,
      amountToSell: 5,
    },
  },
  {
    prefab: 'LoxPelt',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 1,
      time: 90,
      availability: 3,
      complexity: 3,
      amountToSell: 10,
    },
  },
  {
    prefab: 'TrophyLox',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3,
      time: 400,
      availability: 3,
      complexity: 2.5,
      amountToSell: 1,
      balanceCoefficient: 0.8,
    },
  },
  {
    prefab: 'Needle',
    stack: 50,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 1,
      time: 30,
      availability: 3,
      complexity: 2,
      amountToSell: 25,
    },
  },
  {
    prefab: 'TrophyDeathsquito',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3,
      time: 300,
      availability: 3,
      complexity: 2,
      amountToSell: 1,
      balanceCoefficient: 0.8,
    },
  },
  {
    prefab: 'TrophyGrowth',
    stack: 20,
    sellable: true,
    globalKeyToBuy: OGlobalKey.defeatedModer,
    globalKeyToSell: OGlobalKey.defeatedModer,
    pricing: {
      rarity: 3,
      time: 400,
      availability: 3,
      complexity: 2.5,
      amountToSell: 1,
      balanceCoefficient: 0.7,
    },
  },
  {
    prefab: 'TrophyGoblinKing',
    stack: 20,
    sellable: true,
    buyable: false,
    globalKeyToSell: OGlobalKey.defeatedYagluth,
    pricing: {
      rarity: 1,
      time: 90,
      availability: 3,
      complexity: 3,
      amountToSell: 1,
      balanceCoefficient: BOSS_PRICE_BALANCE_MULTIPLIER,
    },
  },
];
